name: Makefile CI

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform:
          - pi
          - radxa
          - rk3528
          - rk3588

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Runner Device
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf cmake make git curl wget gcc qemu-user-static binfmt-support qemu-system-arm

    - name: Build ${{matrix.platform}} Image 
      uses: pguyot/arm-runner-action@v2
      with: 
        image_additional_mb: 4096
        base_image: raspios_lite_arm64:latest
        #bind_mount_repository: true
        #optimize_image: yes
        #copy_repository_path: /opt/pynab
        commands: |    
            sudo apt-get -y update
            sudo apt-get -y install libdrm-dev libcairo-dev build-essential cmake libpcap-dev dkms net-tools wireless-tools libgpiod-dev libi2c-dev i2c-tools
            bash $FN
