name: Makefile CI

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform:
          - pi
          - radxa
          - rk3528
          - rk3588

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Runner Device
      run: |
        sudo apt-get update -y
        sudo apt-get install -y autoconf cmake make git curl wget gcc qemu-user-static binfmt-support qemu-system-arm

    - name: Build ${{matrix.platform}} Image
      id: build_image
      uses: pguyot/arm-runner-action@v2
      with: 
        image_additional_mb: 4096
        base_image: raspios_lite_arm64:latest
        #bind_mount_repository: true
        #optimize_image: yes
        #copy_repository_path: /opt/pynab
        commands: |    
            sudo apt-get -y update
            sudo apt-get -y install libdrm-dev libcairo-dev build-essential cmake libpcap-dev dkms net-tools wireless-tools libgpiod-dev libi2c-dev i2c-tools

            git clone https://github.com/rockchip-linux/mpp.git
            cd mpp
            cmake –B build
            sudo cmake –build build –target install
            cd ..

            git clone https://github.com/svpcom/rtl8812au.git
            cd rtl8812au
            sudo apt-get install dkms
            sudo ./dkms-install.sh
            cd ..

            sudo systemctl disable lightdm
            
            bash $FN

    - name: Upload Image
      run: |
        mv ${{ steps.build_image.outputs.image }} rubyfpv_${{matrix.platform}}.img
        sudo xz -T 0 -v rubyfpv_${{matrix.platform}}.img

    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rubyfpv_${{matrix.platform}}.img.xz
        path: rubyfpv_${{matrix.platform}}.img.xz
        if-no-files-found: error
        retention-days: 3
